### ISSUE TITLE
Specifying a browser is not strictly needed

### ISSUE THREAD

**Issue by tomasruizt** [dfreelon/pyktok#45] opened 2024-05-28 13:00 UTC
Hi,
thank you for sharing your code with the rest of us! I'm eager to build on top of this lib. 

I noticed that I did not need to specify a browser to save tiktok videos. By defining the `cookies=dict()` within the pyktok code I was also able to fetch videos. Perhaps one could also pass `pyktok.specify_browser(None)`, to set `cookies=dict()`. I'm happy to create a PR + test to enable this option, if it makes sense to you.

#### Background
I am running the function `pyktok.save_tiktok()` inside a docker container, and noticed that specyfing the firefox browser and installing it in the image was pretty painful. I needed to:
* install firefox
* try to open firefox within Docker / remotely
* set up a user with empty cookies

**Comment by tomasruizt** [comment] 2024-05-29 16:04
I created a test case that passes with browser=None. If you can add me as a collaborator, I can create the pull request for you to review :) @dfreelon

**Comment by dfreelon** [comment] 2024-05-29 16:07
Well I "assigned" you, and I know others have added PRs without any special privileges, so give it a try and LMK how it goes.

**Comment by tomasruizt** [comment] 2024-05-29 16:13
I can create a pull request with only read access, but I cannot push my branch without write access (https://docs.github.com/en/desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request-from-github-desktop)

This is what I get trying to push my branch:
![image](https://github.com/dfreelon/pyktok/assets/22105494/ade395b6-ca64-461f-8de4-24dfbdb163e9)

Am I perhaps missing something?

**Comment by dfreelon** [comment] 2024-05-29 16:15
Yeah, I have sole write access on this repo and that's by design. Just do your PR, I'll check it out and merge it if it works. Thx

**Comment by tomasruizt** [comment] 2024-05-29 16:27
I'm not able to create a pull request. Here is a video of it: https://www.loom.com/share/911fbac9a12b466997402606f95e89e4?sid=ae022e06-3613-4375-b168-17fffa1dcb0a

**Comment by dfreelon** [comment] 2024-05-29 16:33
Yeah you need to create your own branch and then request to merge with main. Here's an example of one I need to get to but haven't yet--still need to consider how best to integrate it: https://github.com/dfreelon/pyktok/pull/43

**Comment by tomasruizt** [comment] 2024-05-29 16:35
I see! JIV-DLS created a pr from his own. I'll try it out.

**Comment by tomasruizt** [comment] 2024-05-29 16:48
Ok! Its looking good. I was able to create the PR and run its test case automatically on github actions.

**Comment by dfreelon** [comment] 2024-05-29 17:22
Hi, thanks for the PR but I figured out there's an even easier way to implement this--just define the `cookies` global var as an empty dict at the start of the file and you don't have to run `specify_browser` at all (but you can if you want to). So I'll implement that today and close this issue.

**Comment by dfreelon** [comment] 2024-05-29 17:49
OK, just pushed the changes to GitHub and PyPI. Feel free to check it out and LMK if it works for you. In the meantime, I will close this.

**Closed** 2024-05-29 17:49 UTC
