### ISSUE TITLE
AssertionError: Page format changed.

### ISSUE THREAD

**Issue by leoleepsyche** [dfreelon/pyktok#9] opened 2022-12-02 12:04 UTC
when I import the package, it reports that "AssertionError: Page format changed ".  Although this question is a bit silly,  could you point me out a way to fix this problem?

**Comment by dfreelon** [comment] 2022-12-02 14:03
Hi, please provide the error's complete traceback. If it occurs when importing, the issue is almost certainly with one of pyktok's dependencies, and not pyktok itself (also, pyktok does not use `assert`). You can test this by importing all the dependencies one by one and determining which triggers the error.

**Comment by leoleepsyche** [comment] 2022-12-02 14:48
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/var/folders/7r/m23jjtm9061g3s067hngxyqr0000gn/T/ipykernel_1750/295086167.py in <module>
----> 1 import pyktok as pk

/Applications/anaconda3/lib/python3.9/site-packages/pyktok/__init__.py in <module>
----> 1 from .pyktok import *

/Applications/anaconda3/lib/python3.9/site-packages/pyktok/pyktok.py in <module>
     37            'Cache-Control': 'max-age=0',
     38            'Connection': 'keep-alive'}
---> 39 cookies = browser_cookie3.load()
     40 
     41 def deduplicate_metadata(metadata_fn,video_df,dedup_field='video_id'):

/Applications/anaconda3/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(domain_name)
    895     for cookie_fn in [chrome, chromium, opera, brave, edge, vivaldi, firefox, safari]:
    896         try:
--> 897             for cookie in cookie_fn(domain_name=domain_name):
    898                 cj.set_cookie(cookie)
    899         except BrowserCookieError:

/Applications/anaconda3/lib/python3.9/site-packages/browser_cookie3/__init__.py in safari(cookie_file, domain_name)
    886     pass in a domain name to only load cookies from the specified domain
    887     """
--> 888     return Safari(cookie_file, domain_name).load()
    889 
    890 def load(domain_name=""):

/Applications/anaconda3/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(self)
    821         cj = http.cookiejar.CookieJar()
    822         for i in range(self.__total_page):
--> 823             for cookie in self.__parse_page(i):
    824                 if self.__domain_filter(cookie):
    825                     cj.set_cookie(cookie)

/Applications/anaconda3/lib/python3.9/site-packages/browser_cookie3/__init__.py in __parse_page(self, page_index)
    816 
    817         for offset in cookie_offsets:
--> 818             yield self.__parse_cookie(page, offset)
    819 
    820     def load(self):

/Applications/anaconda3/lib/python3.9/site-packages/browser_cookie3/__init__.py in __parse_cookie(self, page, cookie_offset)
    789         value_offset = struct.unpack('<I', page.read(4))[0]
    790 
--> 791         assert page.read(8) == b'\x00' * 8, self.NEW_ISSUE_MESSAGE
    792         expiry_date = int(struct.unpack('<d', page.read(8))[0] + self.APPLE_TO_UNIX_TIME) # convert to unix time
    793         access_time = int(struct.unpack('<d', page.read(8))[0] + self.APPLE_TO_UNIX_TIME) # convert to unix time

AssertionError: Page format changed.
Please create a new issue on: https://github.com/borisbabic/browser_cookie3/issues/new

**Comment by leoleepsyche** [comment] 2022-12-02 14:51
> Thanks for your kind reply. Yes, I have also tested it. it is due to the problems of a package of "browser_cookie3". I have reported this problem to the browser_cookie3 GitHub. but they haven't answered me until now.

**Comment by dfreelon** [comment] 2022-12-02 17:09
Cool, well as this is an issue with another package I'm closing this.

**Closed by dfreelon** 2022-12-02 17:09 UTC

**Comment by leoleepsyche** [comment] 2022-12-02 19:50
> Cool, well as this is an issue with another package I'm closing this.

thanks.
