### ISSUE TITLE
OperationalError: no such column: is_httponly/is_secure

### ISSUE THREAD

**Issue by danmirea** [dfreelon/pyktok#5] opened 2022-10-05 15:37 UTC
Thanks a lot for this package, it looks awesome! I managed to install it and the dependencies, but when I try to run any function I get the following errors:

```
OperationalError                          Traceback (most recent call last)
~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(self)
    306             # chrome <=55
--> 307             cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value, is_httponly '
    308                         'FROM cookies WHERE host_key like ?;', ('%{}%'.format(self.domain_name),))

OperationalError: no such column: is_httponly
```

and

```
~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(self)
    309         except sqlite3.OperationalError:
    310             # chrome >=56
--> 311             cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value, is_httponly '
    312                         'FROM cookies WHERE host_key like ?;', ('%{}%'.format(self.domain_name),))
    313 

OperationalError: no such column: is_secure
```

Have you encountered this broswer_cookie3 issue before? I tried playing with the versions and still nothing. Thanks!

**Comment by danmirea** [comment] 2022-10-09 23:22
Hi there! Thanks for the prompt reply, and sorry for the delay on my part. Here is the information you requested:

OS: macOS Catalina, version 10.17.7
Browsers: Google Chrome, Safari, Firefox
IDE: Jupyter notebooks

Python version: 3.9.13
browser-cookie3 version: 0.16.2

Full traceback (both errors together):
```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(self)
    306             # chrome <=55
--> 307             cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value, is_httponly '
    308                         'FROM cookies WHERE host_key like ?;', ('%{}%'.format(self.domain_name),))

OperationalError: no such column: is_httponly

During handling of the above exception, another exception occurred:

OperationalError                          Traceback (most recent call last)
/var/folders/_z/n5_w9r6511jdpj_g99_tn6h00000gn/T/ipykernel_91970/510959356.py in <cell line: 1>()
----> 1 tiktok_videos = pyk.get_account_video_urls('https://www.tiktok.com/@tiktok')

~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/pyktok/pyktok.py in get_account_video_urls(user_url)
     27 
     28 def get_account_video_urls(user_url):
---> 29     tt_json = get_tiktok_json(user_url)
     30     video_ids = tt_json['ItemList']['user-post']['list']
     31     tt_account = tt_json['UserPage']['uniqueId']

~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/pyktok/pyktok.py in get_tiktok_json(video_url)
     36 
     37 def get_tiktok_json(video_url):
---> 38     cookies = browser_cookie3.load()
     39     tt = requests.get(video_url,
     40                       headers=headers,

~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(domain_name)
    895     for cookie_fn in [chrome, chromium, opera, brave, edge, vivaldi, firefox, safari]:
    896         try:
--> 897             for cookie in cookie_fn(domain_name=domain_name):
    898                 cj.set_cookie(cookie)
    899         except BrowserCookieError:

~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/browser_cookie3/__init__.py in chromium(cookie_file, domain_name, key_file)
    845     domain name to only load cookies from the specified domain
    846     """
--> 847     return Chromium(cookie_file, domain_name, key_file).load()
    848 
    849 

~/opt/anaconda3/envs/pytok/lib/python3.9/site-packages/browser_cookie3/__init__.py in load(self)
    309         except sqlite3.OperationalError:
    310             # chrome >=56
--> 311             cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value, is_httponly '
    312                         'FROM cookies WHERE host_key like ?;', ('%{}%'.format(self.domain_name),))
    313 

OperationalError: no such column: is_secure
```

Let me know if you need other info & thanks so much!

**Comment by dfreelon** [comment] 2022-10-10 12:11
OK, so the issue is definitely with browser_cookie3, and I have not encountered it nor have my grad students. I don't know how far you want to go in trying to solve this issue, but if you have time, please provide the output or tracebacks of the following lines of code (feel free to truncate non-traceback output, for those you can just paste in the first two or three lines):

`browser_cookie3.chrome(domain_name='tiktok.com')`
`browser_cookie3.chrome()`
`browser_cookie3.firefox(domain_name='tiktok.com')`
`browser_cookie3.firefox()`

**Comment by danmirea** [comment] 2022-10-11 17:42
Thanks a lot! I hope to solve this issue as I've been looking for a Tiktok scraper for a while and none of the others have worked. :( 

Strange, I tried all the commands above and all of them give a `NameError: name 'browser_cookie3' is not defined`

e.g.:
```
NameError                                 Traceback (most recent call last)
/var/folders/_z/n5_w9r6511jdpj_g99_tn6h00000gn/T/ipykernel_91970/2285877342.py in <cell line: 1>()
----> 1 browser_cookie3.chrome(domain_name='tiktok.com')

NameError: name 'browser_cookie3' is not defined
```

Then when I directly import browser_cookie3, the functions above seem to work, the output is e.g.:
`<CookieJar[Cookie(version=0, name='_abck', value='F5ADB38DEE89ACDE0382CEEE640BED86~-1~YAAQx+s3FztuVpqDAQAApTU2wAgCJV8zLP818yDDwHyvcY/G1vmeKJXgPrmz0AVs9sXRy4FVc4GUl79Be7zd5Er+WKwoLFJH4FZFrt7mJAg1QNKy0WT4FTeAevx1cVyF2m6uYMOOKU3XJDgpoeqkcpvl9nuSkw1jvVWZUBtkmH9+KYOUACRuuDDbzQGZbGJvJssVMDyhcDnR55jcHMe+4QAlz/3uDTHL/y2x9ovJsDnQhQVuG8YE/DqQDEL+dJAJHezVL5m6996rzAYGMVzBgWmlHmG4tL04uT4Y0V5xUh8e2AxgxHds5wVnFGdSjQj4Qc3e0AOfd16kRLj2Wr1/ldkr+zo7Q2QE3YO8qsLl99BYFZvGWxbDlcD22W1yuh8FDDjY55gTSfKKXA==~-1~-1~-1', port=None, port_specified=False, domain='.tiktok.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=1, expires=1696913121, discard=False, comment=None, comment_url`

But the Pyktok functions still don't work... :(

**Comment by dfreelon** [comment] 2022-10-11 18:09
That's very odd, since that's the output you're supposed to get from browser_cookie3, yet your earlier traceback shows an error. The only other thing I can think of is: does `browser_cookie3.chrome(domain_name='tiktok.com')` work but `browser_cookie3.load()` fail? If that's the problem, I can add an option to `get_tiktok_json` so you can use the former code.

If that's not the issue, I'd be willing to meet with you via Zoom to work on it further. If you're interested in that, please email me (you can get my email address from my personal website) and I will send you my Zoom scheduler link.

**Comment by dfreelon** [comment] 2022-10-24 13:33
If I don't hear anything on this in the next few days, I will close this issue. If anyone else is experiencing it, please reopen.

**Comment by danmirea** [comment] 2022-10-24 23:25
hi! apologies for not replying earlier, I was working on something else. yes, you're completely right - `browser_cookie3.chrome(domain_name='tiktok.com'`) works! if it's not a lot of work, it would be amazing if you could add an option to the existing function! thank you so much!

**Comment by dfreelon** [comment] 2022-10-25 16:43
OK, so I modified the code so that you can now enter a browser as an argument to any function, and `browser_cookie3` should pull the site-specific cookies for that browser. The updated script is here: https://www.dropbox.com/s/uoclvvphfrry0jy/pyktok.py?dl=0 . Here's how you use it:

```python
import pyktok as pyk

pyk.save_tiktok('https://www.tiktok.com/@ging4lyfeee/video/7150656637009693998',True,'tiktok_metadata.csv',browser_name='chrome')
```

You can use any `browser_name` accepted by `browser_cookie3` and installed on your system. Please confirm that this works and I'll incorporate the changes into my next release.

**Comment by dfreelon** [comment] 2022-11-22 22:46
Introduced this functionality into the main branch so closing this issue.

**Closed by dfreelon** 2022-11-22 22:46 UTC
