### ISSUE TITLE
pyk.save_tiktok_multi_page error

### ISSUE THREAD

**Issue by jobreu** [dfreelon/pyktok#44] opened 2024-05-23 14:08 UTC
Thanks for the great library!

I wanted to collect user metadata, but get the following error when running `pyk.save_tiktok_multi_page`:

`TypeError: 'NoneType' object is not subscriptable`

![error_pyktok](https://github.com/dfreelon/pyktok/assets/26274947/ed40777f-f309-4072-a56e-2377bb897794)

I am working with Jupyter Lab, Python v 3.11, OS = Win 10

I have logged in to a TikTok account in Chrome and have closed it before running the command. `pyk.save_tiktok` also works. It is just `pyk.save_tiktok_multi_page` that throws an error. I have tried multiple accounts (including the one from the example code).

**Comment by dfreelon** [comment] 2024-05-26 13:50
Duplicate of #41

**Closed** 2024-05-26 13:51 UTC
Labels: duplicate
