### ISSUE TITLE
ItemModule error while downloading

### ISSUE THREAD

**Issue by LauraPalmer110** [dfreelon/pyktok#53] opened 2024-06-18 13:59 UTC
Hey there! I tried to download videos fro an array of link, and this is the error I got:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[67], line 1
----> 1 pyk.save_tiktok_multi_urls(tiktok_videos,
      2                            False,
      3                      	  'tiktok_data.csv',
      4                      	   1)

File ~\anaconda3\lib\site-packages\pyktok\pyktok.py:334, in save_tiktok_multi_urls(video_urls, save_video, metadata_fn, sleep, browser_name)
    332     tt_urls = video_urls
    333 for u in tt_urls:
--> 334     save_tiktok(u,save_video,metadata_fn,browser_name)
    335     time.sleep(random.randint(1, sleep))
    336 print('Saved',len(tt_urls),'videos and/or lines of metadata')

File ~\anaconda3\lib\site-packages\pyktok\pyktok.py:225, in save_tiktok(video_url, save_video, metadata_fn, browser_name, return_fns)
    222 tt_json = get_tiktok_json(video_url,browser_name)
    224 if tt_json is not None:
--> 225     video_id = list(tt_json['ItemModule'].keys())[0]
    227     if save_video == True:
    228         regex_url = re.findall(url_regex, video_url)[0]

KeyError: 'ItemModule'

For context, I had a column of tiktok links on a Pandas Dataframe, and i turned it into a list. Here's the procedure:

tiktok_videos = df["Link"].tolist()
pyk.save_tiktok_multi_urls(tiktok_videos,
                           False,
                     	  'tiktok_data.csv',
                     	   1)

**Comment by LikeADemonicMind** [comment] 2024-07-03 09:46
Hi! I've got the same error... Have you found any solution?

**Comment by dfreelon** [comment] 2024-07-03 13:11
It would be helpful to see some examples of the URLs you're feeding it... that goes for both of you, thx.

**Comment by dfreelon** [comment] 2024-07-03 13:20
I just tested this and it works for me, so please also verify the version you're using.

**Comment by LikeADemonicMind** [comment] 2024-07-03 13:21
For example: https://www.tiktok.com/@sweetbearoline

I've made some research and found that tt_script = soup.find('script', attrs={'id':"SIGI_STATE"}) (line 183 in pyktok.py) is always None

**Comment by dfreelon** [comment] 2024-07-03 13:23
Line 183 should not be running. Please verify which version you're using.

**Comment by dfreelon** [comment] 2024-07-03 13:25
Also, the function you mentioned requires multiple video URLs and unfortunately cannot download multiple videos from a given user page as you listed. This is a known limitation.

**Comment by dfreelon** [comment] 2024-07-03 13:32
Then your issue is a duplicate of #41 for which there is currently no known solution, unfortunately.

**Comment by LikeADemonicMind** [comment] 2024-07-03 13:35
Oh sorry ^^' thanks a lot for you answer tho! And thanks for the great job!

**Comment by dfreelon** [comment] 2024-07-05 19:35
@LikeADemonicMind, you may be interested in my recent update re #41. @LauraPalmer110 I cannot reproduce your issue without seeing your input data, so you can feel free to post that at your leisure, but I'm closing this for now.

**Closed by dfreelon** 2024-07-05 19:35 UTC
